version: '3'
services:
    app-nginx:
        image: nginx:alpine
        container_name: app-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../:/var/www
            - ./nginx/includes/common.conf:/etc/nginx/conf.d/includes/common.conf
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/certs:/etc/ssl/certs:ro

    app-db:
        container_name: app-db
        image: mariadb:10.5.8
        restart: always
        volumes:
            - ./dump:/var/dump
            - ./data_dir:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"

    app-php:
        build:
            context: ./
            dockerfile: ./php/Dockerfile
        container_name: app-php
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ../:/var/www

    app-redis:
        container_name: app-redis
        image: redis:7.0.11
        ports:
            - 16380:6380
